### ISSUE TITLE
Install Config Override Warn?

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/islandora-starter-site#112]
See the conversation here for more info.

https://github.com/Islandora-Devops/isle-site-template/issues/12

**Comment by adam-vessey** [comment]
Another potential candiate: [Config Override Inspector](https://www.drupal.org/project/coi)

I know [`config_override_warn` in particular indicates](https://www.drupal.org/project/config_override_warn):

> This is not intended to be used on production environments.

From bit of looking, COI may require some additional hook implementations, if we have some odd forms setup for config entities, to help it target the appropriate fields; though, with this targeting, it can actually go and disable the relevant fields/elements, to prevent users from trying to change the values.

**Comment by rosiel** [comment]
The UI from COI is much nicer. 

Here's what Config Override Warn looks like: Fields aren't disabled, and you have to mentally translate the field's machine name into the field in the form.

<img width="1527" alt="Screenshot 2023-10-23 at 12 55 18 PM" src="https://github.com/Islandora-Devops/islandora-starter-site/assets/1943338/93a51739-60d1-451f-87ec-c96605d07cce">


Using COI, (after adding the important info to islandora.settings):

<img width="1088" alt="Screenshot 2023-10-23 at 1 00 01 PM" src="https://github.com/Islandora-Devops/islandora-starter-site/assets/1943338/38e1b373-e6ae-42db-986e-9598432c8985">

I'm leaning to COI, so will make a set of PRs that enable COI on all the currently overridden values.

**Comment by rosiel** [comment]
PRs created for Islandora and IIIF, and for Openseadragon.

The rest of our overrides are for matomo and search_api, which are not COI compatible.

We could create a form alter for these, but where would it be good to put it? Will a form override cause complaints if the form is not found? (My guess is no but just want to make sure).
