### ISSUE TITLE
Move Starter Site to 10.2 [aggregate ticket]

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/islandora-starter-site#121]
This is a place to aggregate things that need to be done during the step to 10.2.

* [Transliterate Filenames is obsolete](https://www.drupal.org/project/transliterate_filenames); all features are part of core. (So, uninstall and remove the module)

**Comment by jordandukart** [comment]
As per the tech call would make sense to remove the `suggest` portion at the same time: https://github.com/Islandora/islandora/blob/2.x/composer.json#L41-L43.

**Comment by rosiel** [comment]
done with https://github.com/Islandora-Devops/islandora-starter-site/pull/123
