### ISSUE TITLE
[BUG] Fedora URI does not appear on repository items where N/A is selected for Display Hint

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/islandora-starter-site#20]
**What steps does it take to reproduce the issue?**

- Start up a site based on islandora-starter-pack
- Create a new repository item (I created a Video Item)
- Select `N/A` for the `Display Hint Field`
- Note that the Fedora URI does not display
- Edit the same object and change `N/A` to Open `Seadragon`
- The Fedora URI now displays

---

* When does this issue occur?

When creating/editing a repository item.

* Which page does it occur on?

The view page for the repository item.

* What happens?

The Fedora URI does not appear when expected.

* To whom does it occur (anonymous visitor, editor, administrator)?

All users regardless of role.

* What did you expect to happen?

The Fedora URI to appear for all objects.

**Which version of Islandora are you using?**

2.4.3 (I was using https://github.com/Islandora/islandora-starter-site/commit/8a32258f3a564180fbc69a8a80c2c4c0f785ebd4 of this repository)

**Any related open or closed issues to this bug report?**

N/A

**Screenshots:**

Settings in question:

![Screenshot 2022-11-08 at 11 53 23](https://user-images.githubusercontent.com/487373/200558218-2abae3a0-7087-45fb-8505-74d5ad72e867.png)

When `N/A` is selected:

![Screenshot 2022-11-08 at 12 00 22](https://user-images.githubusercontent.com/487373/200558625-54477111-befc-4a34-9360-0cc0458f9f92.png)

When `OpenSeadragon is selected`:

![Screenshot 2022-11-08 at 11 59 04](https://user-images.githubusercontent.com/487373/200558465-39f01829-d666-4a7a-9cef-d590c21c3ddb.png)

**Comment by rosiel** [comment]
Great. What should happen?

1.  Fedora URI shows on all display modes
2.  Fedora URI hidden on all display modes
3.  Fedora URI shows on some display modes (hide on collection, for instance?) 

I was gonna propose a 4th, that we use Field Permissions to hide it for unauthenticated users, but Field Permissions doesn't seem to work on Pseudo Fields.

**Comment by nigelgbanks** [comment]
I don't know to be honest what's expected, I would probably go with "#1" as the default. After all, why use fedora if we don't at least provide access to it.

**Comment by rosiel** [comment]
We've changed from using Display Hint to using Viewer Overrides, which avoids this problem. The metadata you see is what's configured on the Default View Mode, regardless of viewer.
