### ISSUE TITLE
[FEATURE] Search view for site and search views for collections.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/islandora-starter-site#23]
**Overview of feature request**
 
 
Something akin to what's currently provided by sandbox.

*Site-wide Search*

![Screenshot 2022-11-09 at 16 56 50](https://user-images.githubusercontent.com/487373/200892678-1d422fbe-9074-42ae-a756-cded61e7e8a6.png)

*Collection Search*

![Screenshot 2022-11-09 at 16 57 11](https://user-images.githubusercontent.com/487373/200892754-437f0635-4d39-4025-b958-71094b3f3187.png)

Ideally with a grid and list display.

The `islandora_advanced_search` is currently not enabled, and if enabled it might suffice along with configuration of Solr fields and facets and views. 

**What kind of user is the feature intended for?**

General users.
 
 
**What inspired the request?**
 
I'm testing changes to `isle-buildkit` and I wanted to test the new version of `solr` was working appropriately.
 
**What existing behavior do you want changed?**
 
N/A
 
**Any brand new behavior do you want to add to Islandora?**
 
N/A (Should all be configuration changes).
 
**Any related open or closed issues to this feature request?**

N/A

**Comment by rosiel** [comment]
Implemented with #70
