### ISSUE TITLE
Use case: Islandora view to show objects that are missing derivatives 

### ISSUE THREAD

**Issue by amyrb** [Islandora-Devops/islandora-starter-site#33]
**Overview of Use Case**
Following the ingest of a collection, there isn't a way to determine via the Islandora/Drupal interface (that I'm aware of) whether all expected derivatives have been generated for the objects in that collection. 

**Title (Goal):** 
Islandora view to show objects that are missing derivatives

**Primary Actor:** 
Collections Manager

**Story:** 
As a repository manager I want to check whether derivatives have generated for a new ingest to my repository. Especially if the ingest is large and the derivatives don't appear in a standard collection view (it can be easy to tell if thumbnails haven't generated), it isn't feasible for me to check the media page for every object in the collection to determine if OCR, service files, or FITS files, for example, are present where they should be; for paged content, thumbnails are also not necessarily easy to check from a standard collection view. If I want to use the Islandora/Drupal interface rather than a script, I need a view that will allow me to see which objects do not have the necessary/expected derivatives. Ideally I would be able to apply this view for a specific collection, and/or for a specific kind of derivative -- my photograph collection probably won't need OCR, but my newspaper collection will; both will need thumbnails.
This would also be helpful for migration QC.

**Comment by rosiel** [comment]
Completed!
