### ISSUE TITLE
duplicate object key "scripts" in the composer file 

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-Devops/islandora-starter-site#76]
https://github.com/Islandora-Devops/islandora-starter-site/blob/main/composer.json#L135
https://github.com/Islandora-Devops/islandora-starter-site/blob/main/composer.json#L144

It seems like a recent PR merge may have introduced a duplicate scripts key.  Thus, composer ignores the tasks in the first scripts key, which places the twig template.  

Combining it as below fixes the issue.

```
    "scripts": {
      "post-root-package-install": [
        "Islandora\\StarterSite::rootPackageInstall"
      ],
      "post-install-cmd": ["cp -f assets/templates/mods.html.twig web/modules/contrib/rest_oai_pmh/templates/mods.html.twig"],
      "post-update-cmd": ["cp -f assets/templates/mods.html.twig web/modules/contrib/rest_oai_pmh/templates/mods.html.twig"]
    },
```

**Comment by seth-shaw-asu** [comment]
@Natkeeran, can you please issue this fix as a PR so we can test and merge?

**Comment by adam-vessey** [comment]
Slapped together #77 to address.
