### ISSUE TITLE
Image Media files are not configured to be stored in Fedora

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-Devops/islandora-starter-site#78]
Should all media (original files, preservation files) be stored in Fedora?

It seems that Images are not being stored in Fedora: https://test.islandora.ca/admin/structure/media/manage/image/fields/media.image.field_media_image/storage

Is there a reason why images are not stored in fedora, while all other media are stored in Fedora?  Should there be consistency with respect to where files/media get stored?

**Comment by seth-shaw-asu** [comment]
Looks like this was accidentally changed with https://github.com/Islandora-Devops/islandora-starter-site/commit/575693148bb644c100374352c2c73880a30a6110.

We just need to switch it back @ https://github.com/Islandora-Devops/islandora-starter-site/blob/b0bb5ffc8a747aa2bbef39fa8a70e4f1cfe38138/config/sync/field.storage.media.field_media_image.yml#L19

Want to issue a PR?
